config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get  'static_pages/home'
  get  'static_pages/help'
  get  'static_pages/about'
  get  'static_pages/contact'
  get  'users/new'
  post 'users/create' 
  get    '/login'  => 'sessions#new'
  post   '/login'  => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><a href="/static_pages/about">About</a></li>
      <li><a href="/static_pages/contact">Contact</a></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container">
    <%= link_to "sample app", href="/static_pages/home", id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li class="nav-item active">
            <a class="nav-link" href="/static_pages/home">Home <span class="sr-only">(current)</span></a>
          </li>
        
       <li class="nav-item">
            <a class="nav-link" href="/static_pages/help">Help</a>
          </li>
        <% if logged_in? %>
          <li class="nav-item">
          <li class="nav-link"><%= link_to "Users", users_path %></li>
          </li>
         <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li class="dropdown-item"><%= link_to "Profile", current_user %></li>
                <li class="dropdown-item"><%= link_to "Settings", edit_user_path(current_user) %></li>
                <a class="divider"></a>
                <li class="dropdown-item"><%= link_to "Log out", logout_path, method: :delete%></li>
              </div>
              </li>
             
            </ul>
          </li>
        <% else %>
       <li class="nav-item">
                <li class="nav-link"><%= link_to "Log in", login_path %></li>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>